languageCode           = "en"
title                  = "crupest's life"
theme                  = "diary"
DefaultContentLanguage = "en"
hasCJKLanguage         = true
enableEmoji            = true
enableGitInfo          = true
copyright              = "by crupest with CC-BY-NC 4.0 license"

[frontmatter]
lastmod = [ "lastmod", ":git", "date", "publishDate" ]

[params]
enableGitalk = true

[params.gitalk]
owner         = "crupest"
repo          = "blog"
client_id     = "d42abdc40e589fa82863"
client_secret = "4ca85252508db58e77122081fd95b73a71f09aec"

[[menu.main]]
url    = "/posts"
name   = "Archive"
weight = 1

[[menu.main]]
url    = "/categories"
name   = "Categories"
weight = 2

[[menu.main]]
url    = "/tags"
name   = "Tags"
weight = 3

[[menu.main]]
url    = "/index.xml"
name   = "RSS Feed"
weight = 5

[[menu.main]]
url    = "/about"
name   = "About"
weight = 4
