baseURL                = "https://blog.crupest.life/"
languageCode           = "zh"
title                  = "crupest 的博客"
theme                  = "diary"
DefaultContentLanguage = "zh"
hasCJKLanguage         = true
enableEmoji            = true
enableGitInfo          = true
copyright              = "crupest. 本站遵循 CC-BY-NC 4.0 协议"

[frontmatter]
lastmod = [ "lastmod", ":git", "date", "publishDate" ]

[params]
enableGitalk = true

[params.gitalk]
owner         = "crupest"
repo          = "crupest.github.io"
client_id     = "d42abdc40e589fa82863"
client_secret = "4ca85252508db58e77122081fd95b73a71f09aec"

[[menu.main]]
url    = "/categories"
name   = "分类"
weight = 2

[[menu.main]]
url    = "/tags"
name   = "标签"
weight = 3

[[menu.main]]
url    = "/posts"
name   = "归档"
weight = 1

[[menu.main]]
url    = "/index.xml"
name   = "RSS Feed"
weight = 5

[[menu.main]]
url    = "/about"
name   = "关于"
weight = 4
